### ISSUE TITLE
Update Computers

### ISSUE THREAD

**Issue by superduperpacman42** [DeepBlueRobotics/RobotCode2016#2]
We need to install the new FRC software on all personal and team computers:
1. Eclipse/plugins: https://wpilib.screenstepslive.com/s/4485/m/13503/l/145002-installing-eclipse-c-java
2. FRC Update Suite: https://wpilib.screenstepslive.com/s/4485/m/13503/l/144150-installing-the-frc-2016-update-suite-all-languages
3. Github (if it's not already downloaded): https://desktop.github.com

**Comment by ana-tudor** [comment]
- Gefen has to fix the XP computers: #2, #7 if internet can be fixed
- Fix internet on #5

-#10 and #3 were not updated

**Comment by ITSmith** [comment]
What is the email and password for the NI account?
