### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by ana-tudor** [DeepBlueRobotics/RobotCode2016#20]
Come up with smartdashboard widget ideas and implement them. Anyone else with ideas can add them to this issue as comments.

**Comment by superduperpacman42** [comment]
Currently Adam is working on the auto chooser widget and Alex Zuckut and Alex Bondarenko are working on the camera widgets.

**Comment by superduperpacman42** [comment]
I am working on the motion profiling widget, Ana has taken over the camera widget, and the auto chooser is pretty much finished.
