### ISSUE TITLE
Image the RoboRIO

### ISSUE THREAD

**Issue by superduperpacman42** [DeepBlueRobotics/RobotCode2016#3]
The firmware update instructions are here: https://wpilib.screenstepslive.com/s/4485/m/13503/l/273817-updating-your-roborio-firmware

Instructions for imaging are here: https://wpilib.screenstepslive.com/s/4485/m/13503/l/144984-imaging-your-roborio

There is also a Java software update: https://wpilib.screenstepslive.com/s/4485/m/13503/l/288822-installing-java-8-on-the-roborio-using-the-frc-roborio-java-installer-java-only

**Comment by ana-tudor** [comment]
Both roboRIOs done, are functional(hopefully).
