### ISSUE TITLE
PID Control

### ISSUE THREAD

**Issue by superduperpacman42** [DeepBlueRobotics/RobotCode2016#9]
We can use last year's code as a starting place, but I think we should make a couple changes to it. Last year's code was designed for each PID loop to rely on a specific sensor, but it turned out that we often wanted to use different inputs for the same outputs (e.g. control the drivetrain with the rangefinder instead of encoders), so we should add a method to input a value in real units, instead of having the PID code do the conversion automatically. It's also worth considering how well the PID code would interface with motion profiling code. There may be other improvements to make as well, so somebody besides me should take a look at it and make revisions.

**Comment by adfost** [comment]
Used 2015 code, mostly completed.

**Comment by abondrn** [comment]
Committed my work on PID from last year. Removed any logic dealing with processing sensor input. If we really want this, it should be managed manually, or at the very least in a separate class.
